name: bob
description: "Powered By Gemini"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.0.0
  intl: ^0.19.0
  fluttertoast: ^8.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  test: ^1.20.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Group1.jpg
    - assets/images/Group2.png
    - assets/images/Group3.png
    - assets/images/Logo.png
    - assets/images/google-gemini-icon.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Logo.png
